version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.PostgresSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.nestJS
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dev:dev@postgres:5432/DB
